---
name: zookeeper

releases:
- name: zookeeper
  version: latest
- name: java
  version: latest


stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest


update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 10-20
  update_watch_time: 10-20

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  vm_type: minimal
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
 
     
